### ISSUE TITLE
Textarea Component

### ISSUE THREAD

**Issue by michael-martin-al** [lifechurch/img-src#10]
Build a responsive textarea component that returns an HTML `<textarea>` tag with the appropriate tachyon class names to match the design below (see the 'Why do you want to be...' field as an example).

***Be sure to read our [Contributor Guidelines](https://github.com/lifechurch/img-src/blob/master/CONTRIBUTING.md) before getting started.***

## Completion Checklist
- [x] Responsive: Does it look equally awesome on big and small screens?
- [x] Does it pass any props it receives onto the returned `<textarea>` tag?
- [x] Does it look like the designs below?

## Desktop Design

![image](https://github.com/lifechurch/img-src/raw/master/ui-design/user-registration/desktop.png)

## Mobile Design

![](https://github.com/lifechurch/img-src/raw/master/ui-design/user-registration/mobile.png)

**Comment by alex-gale** [comment]
There's no `resize: none` class in Tachyons, is it alright if I use a `style` tag for the resize prevention? Also should there be a fancy scrollbar?

**Comment by michael-martin-al** [comment]
@alex-gale I think it should be fine to use the style tag for those two things.
