### ISSUE TITLE
Checkbox Component

### ISSUE THREAD

**Issue by michael-martin-al** [lifechurch/img-src#11]
Build a responsive checkbox component that returns an HTML `<input type="checkbox">` tag plus a label with the appropriate tachyon class names to match the design below (see the 'Why do you want to be...' field as an example).

***Be sure to read our [Contributor Guidelines](https://github.com/lifechurch/img-src/blob/master/CONTRIBUTING.md) before getting started.***

## Completion Checklist
- [x] Responsive: Does it look equally awesome on big and small screens?
- [x] Does it pass any props it receives onto the returned `<input>` tag?
- [x] Does it have an optional prop for providing a `label` next to the checkbox?
- [x] Does it look like the designs below?

## Desktop Design

![image](https://github.com/lifechurch/img-src/raw/master/ui-design/user-registration/desktop.png)

## Mobile Design

![](https://github.com/lifechurch/img-src/raw/master/ui-design/user-registration/mobile.png)

**Comment by FottyM** [comment]
can I get this issue, please?

**Comment by michael-martin-al** [comment]
@FottyM this one hasn't been done. You can have it.
