### ISSUE TITLE
Splash Page

### ISSUE THREAD

**Issue by michael-martin-al** [lifechurch/img-src#12]
Use a combination of components from the `/src/components` folder, HTML elements and Tachyons classes to build a responsive Splash Page matching the designs below.

NOTE, none of the buttons or forms need to do anything. You are merely implementing the design for this page/container.

Feel free to recruit help from the `#yv-image-source` Slack channel in the Open Digerati workspace if you want to pair program or work with a collaborator.

***Be sure to read our [Contributor Guidelines](https://github.com/lifechurch/img-src/blob/master/CONTRIBUTING.md) before getting started.***

Also check out page 3 of the [design overview doc `/src/ui-design/1-design-overview.pdf`](https://github.com/lifechurch/img-src/raw/master/ui-design/1-design-overview.pdf) in this repo for more info about this page.

## Completion Checklist
- [x] Responsive: Does it look equally awesome on big and small screens?
- [x] Does it render for the default route `/`?
- [x] Does it look like the designs below?
- [x] Does the link `Create one here` link to https://www.bible.com/sign-up ?

## Desktop Design

![image](https://github.com/lifechurch/img-src/raw/master/ui-design/splash-page/desktop.png)

## Mobile Design

![](https://github.com/lifechurch/img-src/raw/master/ui-design/splash-page/mobile.png)

**Comment by FottyM** [comment]
@michael-martin-al  should I create a component that changes from photo-collage to carousel or I should just place the images on specific places with css

**Comment by michael-martin-al** [comment]
Sorry @FottyM ... I forgot to respond to you. Just place them with CSS... no need for a carousel here.

**Comment by alex-gale** [comment]
Do you have a logo for the YouVersion text at the top left? @michael-martin-al
