### ISSUE TITLE
User Registration Page

### ISSUE THREAD

**Issue by michael-martin-al** [lifechurch/img-src#13]
Use a combination of components from the `/src/components` folder, HTML elements and Tachyons classes to build a responsive User Registration Page matching the designs below.

NOTE, none of the buttons or forms need to do anything. You are merely implementing the design for this page/container.

Feel free to recruit help from the `#yv-image-source` Slack channel in the Open Digerati workspace if you want to pair program or work with a collaborator.

***Be sure to read our [Contributor Guidelines](https://github.com/lifechurch/img-src/blob/master/CONTRIBUTING.md) before getting started.***

Also check out page 4 of the [design overview doc `/src/ui-design/1-design-overview.pdf`](https://github.com/lifechurch/img-src/raw/master/ui-design/1-design-overview.pdf) in this repo for more info about this page.

## Completion Checklist
- [x] Responsive: Does it look equally awesome on big and small screens?
- [x] Does it render for the default route `/user-registration`?
- [x] Does it look like the designs below?
- [x] Do the form fields have validators?
- [x] Does the `Continue` button stay disabled until the box is checked?
- [x] Does the top form get replaced with the static text after they click Submit?

## Desktop Design

![image](https://github.com/lifechurch/img-src/raw/master/ui-design/user-registration/desktop.png)

## Mobile Design

![](https://github.com/lifechurch/img-src/raw/master/ui-design/user-registration/mobile.png)

## Top Form changes to this after clicking Submit
![](https://github.com/lifechurch/img-src/raw/master/ui-design/user-registration/after-answer.png)

**Comment by alex-gale** [comment]
What kind of validation are we looking for here?

**Comment by michael-martin-al** [comment]
I think built-in HTML5 validation is sufficient. Just add a `required` attribute to each input. Then, use the CSS selectors `input:invalid` and `input:valid` to add some warning color, like a red box-shadow or whatever you think looks best. The browser should automatically display a validation message when the form is submitted if any fields are invalid. See here for more info: https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation
