### ISSUE TITLE
Verse Assignment Page

### ISSUE THREAD

**Issue by michael-martin-al** [lifechurch/img-src#25]
Use a combination of components from the `/src/components` folder, HTML elements and Tachyons classes to build a responsive Verse Assignment Page matching the designs below.

NOTE, none of the buttons or forms need to do anything. You are merely implementing the design for this page/container. You'll need the `<ComboBox>`, `<Card>` and `<ImageDrop>` components from the `/src/components` folder. See issues #1, #14, #16

Also be sure to use the typography components in `/src/components/typograhpy` along with `FormattedMessage` from `react-intl` for all UI text.

Feel free to recruit help from the `#yv-image-source` Slack channel in the Open Digerati workspace if you want to pair program or work with a collaborator.

***Be sure to read our [Contributor Guidelines](https://github.com/lifechurch/img-src/blob/master/CONTRIBUTING.md) before getting started.***

Also check out pages 5, 6 and 7 of the [design overview doc `/src/ui-design/1-design-overview.pdf`](https://github.com/lifechurch/img-src/raw/master/ui-design/1-design-overview.pdf) in this repo for more info about this page.

## Completion Checklist
- [x] Responsive: Does it look equally awesome on big and small screens?
- [x] Does it render for the route `/user-verse-assignment`?
- [x] Does it look like the designs below?
- [x] Are the drop downs for Language and Version built with `ComboBox` components and populated with mock JSON api data?
- [x] Is the list of Cards populated from mock JSON api data and rendered using the `Card` and `ImageDrop` components?

## Desktop Design

![image](https://github.com/lifechurch/img-src/raw/master/ui-design/user-verse-assignment/1-view-desktop.png)

## Mobile Design

![image](https://github.com/lifechurch/img-src/raw/master/ui-design/user-verse-assignment/1-view-mobile.png)

**Comment by tcg** [comment]
👋🏽  Howdy! I see this issue is still tagged as needing mock data. I recently added some preloaded data to the Staging API. If that data doesn't cover the needs for this issue, can you let me know what it needs? I'm happy to add more or adjust as needed! 

// cc @michael-martin-al
