### ISSUE TITLE
Toggle Bar Component

### ISSUE THREAD

**Issue by michael-martin-al** [lifechurch/img-src#27]
Build a responsive toggle bar component that appears as a button bar on `not small` screens and then collapses into a `<select />` or similar drop-down on `small` screens. See the button bar on the User Profile screen for an example.

***Be sure to read our [Contributor Guidelines](https://github.com/lifechurch/img-src/blob/master/CONTRIBUTING.md) before getting started.***

## Completion Checklist
- [x] Responsive: Does it look equally awesome on big and small screens?
- [x] Does it accept an array of Links as children and render them as buttons in the bar?
- [x] Does it render as a drop-down on small screens?
- [x] Does it look like the designs below?

## Desktop Design

![image](https://github.com/lifechurch/img-src/raw/master/ui-design/user-profile/desktop.png)

## Mobile Design

![image](https://github.com/lifechurch/img-src/raw/master/ui-design/user-profile/mobile.png)

**Comment by alex-gale** [comment]
Sorry this one is taking a little longer than usual! Should be done by the end of the weekend
