### ISSUE TITLE
Admin Review Page

### ISSUE THREAD

**Issue by michael-martin-al** [lifechurch/img-src#32]
Use a combination of components from the `/src/components` folder, HTML elements and Tachyons classes to build a responsive User Profile Page matching the designs below.

Feel free to recruit help from the `#yv-image-source` Slack channel in the Open Digerati workspace if you want to pair program or work with a collaborator.

HINT: This is very close to the User Profile Page layout referenced in #29 

***Be sure to read our [Contributor Guidelines](https://github.com/lifechurch/img-src/blob/master/CONTRIBUTING.md) before getting started.***

Also check out page 10 of the [design overview doc `/src/ui-design/1-design-overview.pdf`](https://github.com/lifechurch/img-src/raw/master/ui-design/1-design-overview.pdf) in this repo for more info about this page.

## Completion Checklist
- [ ] Responsive: Does it look equally awesome on big and small screens?
- [x] Does it render for the route `/admin/review`?
- [ ] Does it load a list of images for each category using mock JSON api data?
- [ ] Does it look like the designs below?

## Desktop Design

![image](https://github.com/lifechurch/img-src/raw/master/ui-design/admin/review-desktop.png)

## Mobile Design

![](https://github.com/lifechurch/img-src/raw/master/ui-design/admin/review-mobile.png)

**Comment by tcg** [comment]
👋🏽  Howdy! I see this issue is still tagged as needing mock data. I recently added some preloaded data to the Staging API. If that data doesn't cover the needs for this issue, can you let me know what it needs? I'm happy to add more or adjust as needed! 

// cc @michael-martin-al

**Comment by mroche617** [comment]
@borozcod I'm looking for a way to contribute so if you would like assistance please let me know and I can pull the branch.
