### ISSUE TITLE
Versions dropdown on User Verse Assignment should be populated from API

### ISSUE THREAD

**Issue by michael-martin-al** [lifechurch/img-src#51]
The versions dropdown on the User Verse Assignment page should get its data from the API call. There is a Version model (located here: https://github.com/lifechurch/img-src/blob/master/src/tupos/models/version/index.js) that you use to fetch the list of available versions using the `getMany()` method. For example:

```javascript
import Version from './tupos/models/version'
const versions = await Version.getMany()
const versionItems = versions.map((version) => (
  <li>{version.name}</li>
))
```

**Comment by dbilovd** [comment]
@michael-martin-al can I take a look at this issue? Or it's been assigned already?
