### ISSUE TITLE
Add another React Spinner in user-verse-assignment

### ISSUE THREAD

**Issue by ezrahnyanat** [lifechurch/img-src#74]
Using the `react-spinners` package, bring in a loading spinner for while an image is being uploaded before the `notify` responses flash. You can put the spinner below the image. 

Let's use the PulseLoader http://www.davidhu.io/react-spinners/

**Comment by chocoelho** [comment]
@ezrahnyanat hey there, finally took some time after new year's and tried to implement this, but I'm in doubt regarding one thing: I noticed that the image keeps showing even after the `notify` responses flash. Is this expected? As of now, the spinner follows the image display behavior, but I'm looking into a way to remove the spinner after the notification flash.

![2019-01-12-230707_994x586_scrot](https://user-images.githubusercontent.com/3460435/51080664-ca96f980-16be-11e9-80d8-3207b9757427.png)
---
![2019-01-12-230650_973x579_scrot](https://user-images.githubusercontent.com/3460435/51080666-cd91ea00-16be-11e9-9a38-7c706b8f9bd2.png)

**Comment by michael-martin-al** [comment]
Hey @chocoelho we do want the image to stay on the screen after it loads. If you haven't found a way to remove the spinner after the image loads, you can take a look at the `handleDrop` method in `src/containers/user-verse-assignment/index.js`. Inside there, there are three calls to `this.notify` where we display messages to the user upon success or failure of image upload. After each of these calls, you could add code to hide spinner.
